version: '3.1'

services:
    web:
        image: odoo:15.0
        container_name: odoo
        restart: always
        depends_on:
            - mydb
        ports:
            - "8069:8069"
        environment:
            - HOST=mydb
            - USER=odoo
            - PASSWORD=myodoo
        volumes:
            - odoo-web-data:/var/lib/odoo
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
            - ./modules:/var/lib/odoo/.local/share/Odoo/addons/15.0
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        depends_on:
            - mydb
        ports:
            - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=bvngoc2000@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=dinhngoc2000
        restart: always

    mydb:
        image: postgres:13
        container_name: postgres
        hostname: postgresql
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=myodoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
    odoo-web-data:
    odoo-db-data: